spring.application.name=foodweb

#mangodb configuration

spring.data.mongodb.uri=${MONGO_URI}

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY_ID}
aws.secret.key=${AWS_SECRET_ACCESS_KEY}
aws.region=eu-north-1
aws.s3.bucketName=${AWS_S3_BUCKET_NAME}




jwt.secret.key=${JWT_SECRET_KEY}

#stripe configuration
stripePublishableKey=${STRIPE_PUBLISHABLE_KEY}
stripeSecretKey=${STRIPE_SECRET_KEY}

spring.ai.openai.api-key=${OPENAI_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}


spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB